version: "3.6"
services:
  db:
    container_name : my_sql
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=grocery_booking
      - MYSQL_USER=development
      - MYSQL_PASSWORD=a
      - MYSQL_ROOT_PASSWORD=a
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - grocery-app
    volumes:
      - mysql-data:/data/db

  api:
    container_name: nest_js
    build: .
    ports:
      - 3000:3000
    networks:
      - grocery-app
    depends_on:
      - db


networks:
  grocery-app:
    driver: bridge

volumes:
  mysql-data: {}