version: "3.6"
services:
  server:
    container_name: nestjs
    build: .
    ports:
      - 3001:3000
    depends_on:
      - mysql
    
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=grocery_booking
      - MYSQL_USER=development
      - MYSQL_PASSWORD=a
      - MYSQL_ROOT_PASSWORD=a
    ports:
      - 3307:3306
    expose:
      - 3306
    volumes:
      - mysql-data:/data/db

volumes:
  mysql-data: {}